name: Scrape TitleQuote

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 */8 * * *"  # every 8 hours (UTC)

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          TQ_USERNAME: ${{ secrets.TQ_USERNAME }}
          TQ_PASSWORD: ${{ secrets.TQ_PASSWORD }}
        run: python scraper.py

      - name: Commit & push if changed
        if: success()
        run: |
          set -e
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: update tq_data.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
